# Generated by Django 4.0.2 on 2022-02-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
