# Generated by Django 4.0.3 on 2022-03-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeInfo',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Married_Status', models.CharField(choices=[('1', 'Married'), ('2', 'Unmarried')], default=2, max_length=10)),
                ('Birth_Date', models.DateField(default='Day/Month/Year')),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Number_of_Sibling', models.IntegerField()),
                ('Office_id', models.BigIntegerField(default=1810101, primary_key=True, serialize=False)),
                ('Position_Rank', models.CharField(choices=[('1', 'Worker'), ('2', 'Manager'), ('3', 'HR Manager'), ('4', 'CMO'), ('5', 'CEO')], default=1, max_length=10)),
            ],
            options={
                'ordering': ['Age'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('books_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.books')),
                ('Isbn', models.CharField(max_length=50)),
            ],
            bases=('inheritance.books',),
        ),
    ]
