# Generated by Django 3.2.6 on 2022-02-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
    ]
