# Generated by Django 4.0.3 on 2022-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0003_alter_books_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='Isbn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
