# Generated by Django 4.0.3 on 2022-03-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0005_story_infographicstory_featurestory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfographicStory',
        ),
        migrations.CreateModel(
            name='InfographicStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inheritance.story',),
        ),
    ]
