# Generated by Django 4.0.2 on 2022-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='CSE-101', max_length=20)),
                ('course_name', models.CharField(default='C Language', max_length=50)),
                ('course_credit', models.CharField(choices=[('1', '0.75'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '6')], default='4', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_name', models.CharField(max_length=40)),
                ('std_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('std_email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('course', models.ManyToManyField(to='many.Course')),
            ],
        ),
    ]
